Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.box_version = "20240821.0.1"

    config.vm.define "grafana" do |grafana|
        grafana.vm.network "private_network", ip: "10.2.2.41"
        grafana.vm.network "forwarded_port", guest: 3000, host: 3000
        
        grafana.vm.provider "virtualbox" do |v|
            v.gui = false
            v.memory = "2048"
            v.cpus = 2
            v.name = "grafana"
        end
        grafana.vm.provision "shell", path: "scripts/common.sh"
        grafana.vm.provision "shell", path: "scripts/create_new_user.sh" # Этот скрипт не вошел в список но можно во создать если это не обходимо.
    end 
end